Revamp some more, only test DMG on test step, upload otool info as artifact

diff --git a/.github/workflows/mac_release.yml b/.github/workflows/mac_release.yml
--- a/.github/workflows/mac_release.yml
+++ b/.github/workflows/mac_release.yml
@@ -188,67 +188,63 @@ jobs:
         retention-days: 7
         overwrite: false
 
-    - name: Test Package signing
+    - name: Quick Test Package Signing and otool exes and libs
+      shell: bash
+      working-directory: ./build
+      run: |
+        begin_group() { echo -e "::group::\033[93m$1\033[0m"; }
+
+        subheader() { echo -e "\033[95m---- $1\033[0m"; }
+
+        exes=(
+          "energyplus" "libenergyplusapi.dylib"
+          "ExpandObjects" "ConvertInputFormat"
+          "PreProcess/IDFVersionUpdater/Transition-V23-1-0-to-V23-2-0"
+          "PostProcess/ReadVarsESO" "PostProcess/HVAC-Diagram"
+        )
+
+        TGZ_DIR=$(find _CPack_Packages/Darwin/TGZ -name "EnergyPlus*" -type d -maxdepth 1)
+        echo "TGZ_DIR=$TGZ_DIR" >> $GITHUB_ENV
+        echo "Checking TGZ dir at $TGZ_DIR"
+
+        for rel_exe in "${exes[@]}"; do
+          exe="$TGZ_DIR/$rel_exe"
+          begin_group "Checking $exe"
+          subheader "otool"
+          otool -L "${exe}" || true
+          subheader "codesign"
+          siginfo=$(codesign --display -vv "${exe}" 2>&1)
+          if [[ $siginfo == *"K7JYVQJL7R"* ]]; then
+            echo -e "\033[92mSIGNATURE OK\033[0m"
+            echo "$siginfo" | grep Authority
+          else
+            echo -e "\033[91mSignature not ok for ${exe}\033[0m"
+            echo "::error::title=Signature not ok for ${exe}::$siginfo"
+          fi
+          echo "::endgroup::"
+        done
+
+    - name: Full Test Package signing and otool for IFW and TGZ
       working-directory: ./build
       shell: bash
       run: |
         begin_group() { echo -e "::group::\033[93m$1\033[0m"; }
 
-        set -x
-
-        dmg=$(ls EnergyPlus-*.dmg)
-        begin_group "Checking Signature of .dmg"
-        spctl --assess --type open --context context:primary-signature -vvvv $dmg
-        echo "::endgroup::"
-
-        begin_group "Mounting Dmg, and checking signature of installer app"
-        mkdir temp_mount
-        hdiutil attach -mountpoint ./temp_mount/ $dmg
-        filename="${dmg%.*}"
-        spctl --assess --type open --context context:primary-signature -vvvv ./temp_mount/$filename.app
-
-        begin_group "Installing"
-        sudo ./temp_mount/$filename.app/Contents/MacOS/$filename --accept-licenses --default-answer --confirm-command --root $(pwd)/test_install install
-        hdiutil detach ./temp_mount/
-        echo "::endgroup::"
-
-        begin_group "Checking signature of inner executables and binaries"
-        codesign -dvvv ./test_install/energyplus
-        codesign -dvvv ./test_install/libenergyplusapi.dylib
-        codesign -dvvv ./test_install/libpython*.dylib
-        codesign -dvvv ./test_install/ConvertInputFormat
-        echo "::endgroup::"
-
-        begin_group "Full Check signature of _CPack_Packages for both IFW and TGZ"
-        python ../scripts/dev/verify_signature.py --verbose .
-        echo "::endgroup::"
-
-        begin_group "Full Check signature of installed DMG for all executables"
-        python ../scripts/dev/verify_signature.py --install --verbose test_install
+        begin_group "Full Check signature of _CPack_Packages for both IFW and TGZ and resolve otool libraries"
+        python ../scripts/dev/verify_signature.py --verbose --otool --otool-out-file otool_infos_cpack.json .
         echo "::endgroup::"
 
         begin_group "Running a simulation with python"
-        ./test_install/energyplus --help
-        ./test_install/energyplus -w ./test_install/WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw -d out ./test_install/ExampleFiles/PythonPluginCustomSchedule.idf
+        ./$TGZ_DIR/energyplus --help
+        ./$TGZ_DIR/energyplus -w ./$TGZ_DIR/WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw -d out ./$TGZ_DIR/ExampleFiles/PythonPluginCustomSchedule.idf
         echo "::endgroup::"
 
-#    - name: Setup tmate session
-#      if: ${{ always() }}
-#      uses: mxschmitt/action-tmate@v3
-
-    - name: otool the exes and libs
-      shell: bash
-      working-directory: ./build
-      run: |
-        set -x
-        cd _CPack_Packages/Darwin/TGZ/EnergyPlus*/
-        otool -L ExpandObjects || true
-        otool -L ConvertInputFormat || true
-        otool -L energyplus || true
-        otool -L libenergyplusapi.dylib || true
-        otool -L PreProcess/IDFVersionUpdater/Transition-V23-1-0-to-V23-2-0 || true
-        otool -L PostProcess/ReadVarsESO || true
-        otool -L PostProcess/HVAC-Diagram || true
+    - name: Upload otool info as artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: otool_infos_cpack
+        path: build/otool*json
+        if-no-files-found: error
 
     - name: Upload Tarball to release
       uses: svenstaro/upload-release-action@v2
@@ -288,78 +284,86 @@ jobs:
             test_key: mac13-arm64
 
     steps:
-      - uses: actions/checkout@v4  # Still need E+ checked out to get testing scripts
-        with:
-          path: checkout
+    - uses: actions/checkout@v4  # Still need E+ checked out to get testing scripts
+      with:
+        path: checkout
 
-      - name: Set up Python ${{ env.Python_REQUIRED_VERSION }}
-        uses: actions/setup-python@v5
-        id: setup-python
-        with:
-          python-version: ${{ env.Python_REQUIRED_VERSION }}
-          architecture: ${{ matrix.python-arch }}
+    - name: Set up Python ${{ env.Python_REQUIRED_VERSION }}
+      uses: actions/setup-python@v5
+      id: setup-python
+      with:
+        python-version: ${{ env.Python_REQUIRED_VERSION }}
+        architecture: ${{ matrix.python-arch }}
 
-      - name: Gather Test Package from Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: energyplus-${{ matrix.os }}.tar.gz
-          path: package
+    - name: Gather Test Package from Artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: energyplus-${{ matrix.os }}.tar.gz
+        path: package
 
-      - name: Check Contents
-        shell: bash
-        run: ls
+    - name: Check Contents
+      shell: bash
+      run: ls
 
-      - name: Check Package contents
-        shell: bash
-        working-directory: package
-        run: ls
+    - name: Check Package contents
+      shell: bash
+      working-directory: package
+      run: ls
 
-      - name: Run Package Tests
-        run: python checkout/scripts/package_tests/runner.py --verbose ${{ matrix.test_key }} package/
+    - name: Run Package Tests
+      run: python checkout/scripts/package_tests/runner.py --verbose ${{ matrix.test_key }} package/
 
-      - name: Gather Dmg Package from Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: energyplus-${{ matrix.os }}.dmg
-          path: dmg
+    - name: Gather Dmg Package from Artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: energyplus-${{ matrix.os }}.dmg
+        path: dmg
 
-      - name: Test Dmg Package signing
-        working-directory: ./dmg
-        shell: bash
-        run: |
-          begin_group() { echo -e "::group::\033[93m$1\033[0m"; }
+    - name: Test Dmg Install and Package signing
+      working-directory: ./dmg
+      shell: bash
+      run: |
+        begin_group() { echo -e "::group::\033[93m$1\033[0m"; }
 
-          set -x
+        set -x
 
-          dmg=$(ls EnergyPlus-*.dmg)
-          begin_group "Checking Signature of .dmg"
-          spctl --assess --type open --context context:primary-signature -vvvv $dmg
-          echo "::endgroup::"
+        dmg=$(ls EnergyPlus-*.dmg)
+        begin_group "Checking Signature of .dmg"
+        spctl --assess --type open --context context:primary-signature -vvvv $dmg
+        echo "::endgroup::"
 
-          begin_group "Mounting Dmg, and checking signature of installer app"
-          mkdir temp_mount
-          hdiutil attach -mountpoint ./temp_mount/ $dmg
-          filename="${dmg%.*}"
-          spctl --assess --type open --context context:primary-signature -vvvv ./temp_mount/$filename.app
+        begin_group "Mounting Dmg, and checking signature of installer app"
+        mkdir temp_mount
+        hdiutil attach -mountpoint ./temp_mount/ $dmg
+        filename="${dmg%.*}"
+        spctl --assess --type open --context context:primary-signature -vvvv ./temp_mount/$filename.app
+        echo "::endgroup::"
 
-          begin_group "Installing"
-          sudo ./temp_mount/$filename.app/Contents/MacOS/$filename --accept-licenses --default-answer --confirm-command --root $(pwd)/test_install install
-          hdiutil detach ./temp_mount/
-          echo "::endgroup::"
+        begin_group "Installing"
+        sudo ./temp_mount/$filename.app/Contents/MacOS/$filename --accept-licenses --default-answer --confirm-command --root $(pwd)/test_install install
+        hdiutil detach ./temp_mount/
+        echo "::endgroup::"
 
-          begin_group "Checking signature of inner executables and binaries"
-          codesign -dvvv ./test_install/energyplus
-          codesign -dvvv ./test_install/libenergyplusapi.dylib
-          codesign -dvvv ./test_install/libpython*.dylib
-          codesign -dvvv ./test_install/ConvertInputFormat
-          codesign -dvvv ./test_install/PostProcess/ReadVarsESO
-          echo "::endgroup::"
+        begin_group "Quick Check signature of inner executables and binaries"
+        codesign -dvvv ./test_install/energyplus
+        codesign -dvvv ./test_install/libenergyplusapi.dylib
+        codesign -dvvv ./test_install/libpython*.dylib
+        codesign -dvvv ./test_install/ConvertInputFormat
+        codesign -dvvv ./test_install/PostProcess/ReadVarsESO
+        echo "::endgroup::"
 
-          begin_group "Full Check signature of installed DMG for all executables"
-          python ../checkout/scripts/dev/verify_signature.py --install --verbose test_install
-          echo "::endgroup::"
+        begin_group "Full Check signature of installed DMG for all executables and resolve otool libraries"
+        python ../checkout/scripts/dev/verify_signature.py --otool --otool-out-file otool_info_dmg.json --verbose --install test_install
+        echo "::endgroup::"
 
-          begin_group "Running a simulation with python"
-          ./test_install/energyplus --help
-          ./test_install/energyplus -w ./test_install/WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw -d out ./test_install/ExampleFiles/PythonPluginCustomSchedule.idf
-          echo "::endgroup::"
+        begin_group "Running a simulation with python"
+        ./test_install/energyplus --help
+        ./test_install/energyplus -w ./test_install/WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw -d out ./test_install/ExampleFiles/PythonPluginCustomSchedule.idf
+        echo "::endgroup::"
+
+    - name: Upload otool info as artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: otool_info_dmg
+        path: dmg/otool*json
+        if-no-files-found: error
